<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<!-- ORM e banco -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="8.21.121" />
		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<!-- Logging estruturado -->
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
		<!-- Health Checks -->
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.0" />
		<!-- OpenTelemetry -->
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.8.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.11" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.7.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.7.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="0.5.0-beta.4" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.7.0-rc.1" />
		<!-- JWT -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
		<!-- MongoDB -->
		<PackageReference Include="MongoDB.Driver" Version="2.27.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\PortariaLight.Application\PortariaLight.Application.csproj" />
		<ProjectReference Include="..\PortariaLight.Infrastructure\PortariaLight.Infrastructure.csproj" />
	</ItemGroup>
</Project>